### ISSUE TITLE
I've found your phone

### ISSUE THREAD

**Issue by jtruetsch** [conradteichmann/lost#1]
In Schlossgarten.

**Comment by conradteichmann** [comment]
Noch mal vielen vielen Dank, dass ihr es gefunden habt und euch so bemüht habt, mich zu kontaktieren.

Da hat dieses tolle Testprojekt hier ja sogar einen Sinn bekommen :D

**Comment by jtruetsch** [comment]
Kein Ding :-) Wir waren uns aber für einen kurzen Moment nicht ganz sicher, ob wir nicht unbeabsichtigt Teil einer Schnitzeljagd geworden sind, nachdem wir auf deinem GitHub ein repository mit dem Namen "lost" gefunden haben :-D
